 有一堆彩色球， 红黄蓝绿紫等等， 现在给你一个概率的list/dict, 比方说红20%， 黄30%， 蓝50%， 你给我写个程序抽球(sample)。Sampling from a huge number of colored balls

In [36]:
prob = {'red': 0.2, 'yellow': 0.3, 'blue': 0.5}
# The colors (groups) of a bag of balls may or maynot be the same as the keys of prob
colors = ['red', 'yellow', 'blue'] 
# function to pick the ball with certain probality
import numpy as np
def pick_ball(colors, num, prob):
    return np.random.choice(colors, num, prob)

In [48]:
for i in range(10):
    print(pick_ball(colors, 1, prob)[0])

red
yellow
red
blue
blue
blue
red
blue
red
yellow


In [45]:
def pick_n_balls(n):
    balls = {}
    while n > 0:
        color = pick_ball(colors, 1, prob)[0]
        balls[color] = balls.get(color, 0) + 1
        n-=1
    return balls

In [22]:
pick_n_balls(1000)

{'yellow': 327, 'red': 335, 'blue': 338}

numpy.random.sample

In [52]:
np.random.random_sample()

0.21949529581674654

In [53]:
np.random.sample()

0.30753205461353494

In [54]:
np.random.random_sample(4)

array([0.72312526, 0.43891366, 0.89168591, 0.45354253])

In [56]:
np.random.random_sample((4, 1))

array([[0.08012933],
       [0.73724056],
       [0.55333936],
       [0.72307298]])

In [58]:
np.random.sample((1, 4))

array([[0.90440711, 0.68876144, 0.869219  , 0.30776837]])

### random int from low and high, inclusive

In [61]:
np.random.random_integers(5, size=(3,2))

<ipython-input-61-f64c301fced7>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5, size=(3,2))


array([[5, 4],
       [3, 5],
       [2, 3]])

In [65]:
np.random.randint(5, size=(3,2)) #high (exclusive).

array([[2, 1],
       [2, 0],
       [4, 1]])

## use random.random() or random.choice()

In [142]:
# use random.random() 
import random
prob = [('red', 0.2), ('yellow', 0.3), ('blue', 0.5)]
# get a number between (0, 0.2), (0.2, 0.5), (0.5, 1)

# function to pick the ball with specified probality for each colors
def pick_a_ball(prob):
    randint_rng = []
    upper = 0
    lower = 0
    for i, x in enumerate(prob):
        lower = upper
        upper += x[1] # map the probability to a range.
        randint_rng.append((x[0], lower, upper))
#     print(f'ball\'s color and its range: {randint_rng}')
    # pick the ball with a random number
    num = random.random()
    for rng in randint_rng:
        if rng[1] <= num < rng[2]:
            return rng[0]

In [143]:
pick_a_ball(prob)

'blue'

In [151]:
res = []
for i in range(10000):
    res.append(pick_a_ball(prob))
    
from collections import Counter
Counter(res)

Counter({'blue': 4973, 'red': 2080, 'yellow': 2947})